<a href="https://colab.research.google.com/github/LucianaNorat/eleicoes-pcd-2024-pb/blob/main/Eleitores_pcd_2024_TESTE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ETL — Eleitores PCD 2024 PB
**Projeto:** BD Eleições PCD 2024 | **Equipe:** Luciana Norat, Mônica Vasconcelos
**Checkpoint:** C3 | Organização: Bronze → Silver → Gold

## 1. Bronze — Extração bruta das 3 fontes TSE

In [ ]:
# Conecta o Google Drive ao Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import zipfile

# Extrai o ZIP direto do Drive para o Colab
with zipfile.ZipFile('/content/drive/MyDrive/Dissertacao_TSE/perfil_eleitor_secao_2024_PB.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/drive/MyDrive/Dissertacao_TSE/')

print("Extração concluída!")

Extração concluída!

In [ ]:
import pandas as pd

# Lê o arquivo CSV
df = pd.read_csv(
    '/content/drive/MyDrive/Dissertacao_TSE/perfil_eleitor_secao_2024_PB.csv',
    sep=';',
    encoding='latin1',
    low_memory=False
)

# Mostra as primeiras linhas
df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,...,DS_IDENTIDADE_GENERO,CD_QUILOMBOLA,DS_QUILOMBOLA,CD_INTERPRETE_LIBRAS,DS_INTERPRETE_LIBRAS,TP_OBRIGATORIEDADE_VOTO,QT_ELEITORES_PERFIL,QT_ELEITORES_BIOMETRIA,QT_ELEITORES_DEFICIENCIA,QT_ELEITORES_INC_NM_SOCIAL
0,13/09/2024,15:32:22,2024,PB,21415,POCINHOS,50,15,1031,COLEGIO MUNICIPAL PADRE GALVAO,...,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,Obrigatório,2,2,0,0
1,13/09/2024,15:32:22,2024,PB,20516,JOÃO PESSOA,64,1,1082,ESCOLA NORMAL ESTADUAL PROFESSORA MARIA DO CAR...,...,Cisgênero,2,NÃO,2,NÃO,Obrigatório,1,1,0,0
2,13/09/2024,15:32:22,2024,PB,20117,VISTA SERRANA,51,28,1104,ESCOLA MUNICIPAL DE 1º E 2º GRAUS JOSÉ GIL XAV...,...,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,Obrigatório,1,1,0,0
3,13/09/2024,15:32:22,2024,PB,19810,CAMPINA GRANDE,17,344,1627,CEAI ANTÔNIO MARIZ,...,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,Obrigatório,1,1,0,0
4,13/09/2024,15:32:22,2024,PB,19798,CAMALAÚ,29,175,1147,E.M.E.F. FRANCISCO CHAVES VENTURA,...,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,Facultativo,1,1,0,0

In [ ]:
# Quantas linhas e colunas tem o arquivo?
print("Tamanho do dataset:")
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")

print("\nNome de todas as colunas:")
print(df.columns.tolist())

print("\nQuantos eleitores com deficiência no total?")
print(df['QT_ELEITORES_DEFICIENCIA'].sum())

Tamanho do dataset:
Linhas: 1810719
Colunas: 31

Nome de todas as colunas:
['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'SG_UF', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_ZONA', 'NR_SECAO', 'NR_LOCAL_VOTACAO', 'NM_LOCAL_VOTACAO', 'CD_GENERO', 'DS_GENERO', 'CD_ESTADO_CIVIL', 'DS_ESTADO_CIVIL', 'CD_FAIXA_ETARIA', 'DS_FAIXA_ETARIA', 'CD_GRAU_ESCOLARIDADE', 'DS_GRAU_ESCOLARIDADE', 'CD_RACA_COR', 'DS_RACA_COR', 'CD_IDENTIDADE_GENERO', 'DS_IDENTIDADE_GENERO', 'CD_QUILOMBOLA', 'DS_QUILOMBOLA', 'CD_INTERPRETE_LIBRAS', 'DS_INTERPRETE_LIBRAS', 'TP_OBRIGATORIEDADE_VOTO', 'QT_ELEITORES_PERFIL', 'QT_ELEITORES_BIOMETRIA', 'QT_ELEITORES_DEFICIENCIA', 'QT_ELEITORES_INC_NM_SOCIAL']

Quantos eleitores com deficiência no total?
24279

## 1.1 Exploração inicial (sanity check — não faz parte do pipeline formal)

In [ ]:
# Total de eleitores PCD por zona eleitoral
pcd_por_zona = df.groupby('NR_ZONA')['QT_ELEITORES_DEFICIENCIA'].sum()
pcd_por_zona = pcd_por_zona.sort_values(ascending=False)

print("Top 10 zonas com mais eleitores PCD:")
print(pcd_por_zona.head(10))

Top 10 zonas com mais eleitores PCD:
NR_ZONA
77    1352
17    1041
72    1001
64     874
1      865
76     851
16     848
70     794
68     656
28     654
Name: QT_ELEITORES_DEFICIENCIA, dtype: int64

In [ ]:
# Qual município corresponde a cada zona?
zona_municipio = df.groupby(['NR_ZONA', 'NM_MUNICIPIO'])['QT_ELEITORES_DEFICIENCIA'].sum()
zona_municipio = zona_municipio.sort_values(ascending=False)

print("Top 10 zonas com município:")
print(zona_municipio.head(10))

Top 10 zonas com município:
NR_ZONA  NM_MUNICIPIO
77       JOÃO PESSOA       1352
17       CAMPINA GRANDE    1041
72       CAMPINA GRANDE     949
64       JOÃO PESSOA        874
1        JOÃO PESSOA        865
76       JOÃO PESSOA        851
70       JOÃO PESSOA        794
16       CAMPINA GRANDE     732
28       PATOS              637
61       BAYEUX             574
Name: QT_ELEITORES_DEFICIENCIA, dtype: int64

In [ ]:
# Ver total de eleitores (com e sem deficiência) por município
# para comparar e identificar possível subnotificação
resumo = df.groupby('NM_MUNICIPIO').agg(
    total_eleitores=('QT_ELEITORES_PERFIL', 'sum'),
    total_pcd=('QT_ELEITORES_DEFICIENCIA', 'sum')
).reset_index()

# Calcula o percentual de PCD sobre o total
resumo['percentual_pcd'] = (resumo['total_pcd'] / resumo['total_eleitores'] * 100).round(2)

# Ordena pelo total de eleitores (maiores municípios primeiro)
resumo = resumo.sort_values('total_eleitores', ascending=False)

print("Top 15 municípios mais populosos e seus eleitores PCD:")
print(resumo.head(15).to_string(index=False))

Top 15 municípios mais populosos e seus eleitores PCD:
  NM_MUNICIPIO  total_eleitores  total_pcd  percentual_pcd
   JOÃO PESSOA           566290       4736            0.84
CAMPINA GRANDE           298888       2722            0.91
    SANTA RITA           101702        623            0.61
        BAYEUX            75831        574            0.76
         PATOS            68104        637            0.94
      CABEDELO            54561        418            0.77
    CAJAZEIRAS            47610        536            1.13
         SOUSA            47538        332            0.70
     GUARABIRA            43183        252            0.58
          SAPÉ            37342        224            0.60
     QUEIMADAS            36154        332            0.92
    MAMANGUAPE            34144        290            0.85
     SÃO BENTO            29525        109            0.37
         CONDE            27264        200            0.73
      MONTEIRO            27058        185            0.68

## 1.2 Bronze — Arquivo 2 (comparecimento/abstenção)

Extraindo os dados do arquivo de comparecimento abstenção de 2024

In [ ]:
import os

caminho = '/content/drive/MyDrive/Dissertacao_TSE/'
print(os.listdir(caminho))

['perfil_eleitor_secao_2024_PB.zip', 'perfil_eleitor_secao_2024_PB.csv', 'perfil_comparecimento_abstencao_2024.zip', 'perfil_comparecimento_abstencao_2024_BRASIL.csv', 'perfil_comparecimento_abstencao_2024_PB.csv', 'leiame.pdf', 'eleitorado_local_votacao_2024_PB.csv']

In [ ]:
import zipfile

with zipfile.ZipFile('/content/drive/MyDrive/Dissertacao_TSE/perfil_comparecimento_abstencao_2024.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/drive/MyDrive/Dissertacao_TSE/')

print("Extração concluída!")

Extração concluída!

In [ ]:
import os

caminho = '/content/drive/MyDrive/Dissertacao_TSE/'
print(os.listdir(caminho))

['perfil_eleitor_secao_2024_PB.zip', 'perfil_eleitor_secao_2024_PB.csv', 'perfil_comparecimento_abstencao_2024.zip', 'perfil_comparecimento_abstencao_2024_BRASIL.csv', 'perfil_comparecimento_abstencao_2024_PB.csv', 'leiame.pdf', 'eleitorado_local_votacao_2024_PB.csv', 'perfil_comparecimento_abstencao_2024_AC.csv', 'perfil_comparecimento_abstencao_2024_MT.csv', 'perfil_comparecimento_abstencao_2024_AL.csv', 'perfil_comparecimento_abstencao_2024_BA.csv', 'perfil_comparecimento_abstencao_2024_AM.csv', 'perfil_comparecimento_abstencao_2024_AP.csv', 'perfil_comparecimento_abstencao_2024_PA.csv', 'perfil_comparecimento_abstencao_2024_MS.csv', 'perfil_comparecimento_abstencao_2024_CE.csv', 'perfil_comparecimento_abstencao_2024_ES.csv', 'perfil_comparecimento_abstencao_2024_MA.csv', 'perfil_comparecimento_abstencao_2024_GO.csv', 'perfil_comparecimento_abstencao_2024_MG.csv', 'perfil_comparecimento_abstencao_2024_PE.csv', 'perfil_comparecimento_abstencao_2024_PI.csv', 'perfil_comparecimento_abstencao_2024_PR.csv', 'perfil_comparecimento_abstencao_2024_RJ.csv', 'perfil_comparecimento_abstencao_2024_RN.csv', 'perfil_comparecimento_abstencao_2024_RO.csv', 'perfil_comparecimento_abstencao_2024_RR.csv', 'perfil_comparecimento_abstencao_2024_RS.csv', 'perfil_comparecimento_abstencao_2024_SC.csv', 'perfil_comparecimento_abstencao_2024_SE.csv', 'perfil_comparecimento_abstencao_2024_SP.csv', 'perfil_comparecimento_abstencao_2024_TO.csv']

In [ ]:
import pandas as pd

df_comparecimento = pd.read_csv(
    '/content/drive/MyDrive/Dissertacao_TSE/perfil_comparecimento_abstencao_2024_PB.csv',
    sep=';',
    encoding='latin1',
    low_memory=False
)

df_comparecimento.head()

print("Tamanho do dataset:")
print(f"Linhas: {df_comparecimento.shape[0]}")
print(f"Colunas: {df_comparecimento.shape[1]}")

print("\nNome de todas as colunas:")
print(df_comparecimento.columns.tolist())

Tamanho do dataset:
Linhas: 302946
Colunas: 43

Nome de todas as colunas:
['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'NR_TURNO', 'SG_UF', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_ZONA', 'CD_GENERO', 'DS_GENERO', 'CD_ESTADO_CIVIL', 'DS_ESTADO_CIVIL', 'CD_FAIXA_ETARIA', 'DS_FAIXA_ETARIA', 'CD_GRAU_ESCOLARIDADE', 'DS_GRAU_ESCOLARIDADE', 'CD_COR_RACA', 'DS_COR_RACA', 'CD_QUILOMBOLA', 'DS_QUILOMBOLA', 'CD_INTERPRETE_LIBRAS', 'DS_INTERPRETE_LIBRAS', 'CD_IDENTIDADE_GENERO', 'DS_IDENTIDADE_GENERO', 'CD_IDIOMA_INDIGENA', 'DS_IDIOMA_INDIGENA', 'CD_GRUPO_INDIGENA', 'DS_GRUPO_INDIGENA', 'QT_APTOS', 'QT_COMPARECIMENTO', 'QT_ABSTENCAO', 'QT_COMPARECIMENTO_DEFICIENCIA', 'QT_ABSTENCAO_DEFICIENCIA', 'QT_COMPARECIMENTO_TTE', 'QT_ABSTENCAO_TTE', 'QT_COMPAREC_FACULTATIVO', 'QT_ABST_FACULTATIVO', 'QT_COMPAREC_OBRIGATORIO', 'QT_ABST_OBRIGATORIO', 'QT_COMPAREC_DEFIC_FACULTATIVO', 'QT_ABST_DEFIC_FACULTATIVO', 'QT_COMPAREC_DEFIC_OBRIGATORIO', 'QT_ABST_DEFIC_OBRIGATORIO']

## 1.3 Bronze — Arquivo 3 (locais de votação e acessibilidade)

In [ ]:
import requests

url = "https://cdn.tse.jus.br/estatistica/sead/odsele/eleitorado_locais_votacao/eleitorado_local_votacao_2024.zip"
destino = "/content/eleitorado_local_votacao_2024.zip"

resposta = requests.get(url)
with open(destino, "wb") as f:
    f.write(resposta.content)

print("Download concluído!")

import zipfile

with zipfile.ZipFile('/content/eleitorado_local_votacao_2024.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/eleitorado_local_votacao/')

print("Extração concluída!")

import os
print(os.listdir('/content/eleitorado_local_votacao/'))

Download concluído!
Extração concluída!
['eleitorado_local_votacao_2024.csv', 'leiame.pdf']

In [ ]:
import pandas as pd

# Lê o CSV nacional (ainda no disco do Colab, não no Drive)
df_local_votacao = pd.read_csv(
    '/content/eleitorado_local_votacao/eleitorado_local_votacao_2024.csv',
    sep=';',
    encoding='latin1',
    low_memory=False
)

print("Tamanho do dataset (Brasil todo):")
print(f"Linhas: {df_local_votacao.shape[0]}")
print(f"Colunas: {df_local_votacao.shape[1]}")

print("\nNome de todas as colunas:")
print(df_local_votacao.columns.tolist())

Tamanho do dataset (Brasil todo):
Linhas: 599204
Colunas: 41

Nome de todas as colunas:
['DT_GERACAO', 'HH_GERACAO', 'AA_ELEICAO', 'DT_ELEICAO', 'DS_ELEICAO', 'NR_TURNO', 'SG_UF', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_ZONA', 'NR_SECAO', 'CD_TIPO_SECAO_AGREGADA', 'DS_TIPO_SECAO_AGREGADA', 'NR_SECAO_PRINCIPAL', 'NR_LOCAL_VOTACAO', 'NM_LOCAL_VOTACAO', 'CD_TIPO_LOCAL', 'DS_TIPO_LOCAL', 'DS_ENDERECO', 'NM_BAIRRO', 'NR_CEP', 'NR_TELEFONE_LOCAL', 'NR_LATITUDE', 'NR_LONGITUDE', 'CD_SITU_LOCAL_VOTACAO', 'DS_SITU_LOCAL_VOTACAO', 'CD_SITU_ZONA', 'DS_SITU_ZONA', 'CD_SITU_SECAO', 'DS_SITU_SECAO', 'CD_SITU_LOCALIDADE', 'DS_SITU_LOCALIDADE', 'CD_SITU_SECAO_ACESSIBILIDADE', 'DS_SITU_SECAO_ACESSIBILIDADE', 'QT_ELEITOR_SECAO', 'QT_ELEITOR_ELEICAO_FEDERAL', 'QT_ELEITOR_ELEICAO_ESTADUAL', 'QT_ELEITOR_ELEICAO_MUNICIPAL', 'NR_LOCAL_VOTACAO_ORIGINAL', 'NM_LOCAL_VOTACAO_ORIGINAL', 'DS_ENDERECO_LOCVT_ORIGINAL']

In [ ]:
# Filtra só os registros da Paraíba
df_local_votacao_pb = df_local_votacao[df_local_votacao['SG_UF'] == 'PB'].copy()

print(f"Registros da PB: {df_local_votacao_pb.shape[0]}")

# Quais são os valores possíveis da coluna de acessibilidade?
print("\nValores únicos de acessibilidade:")
print(df_local_votacao_pb['DS_SITU_SECAO_ACESSIBILIDADE'].value_counts())

Registros da PB: 13240

Valores únicos de acessibilidade:
DS_SITU_SECAO_ACESSIBILIDADE
Sem acessibilidade    6675
Com acessibilidade    6565
Name: count, dtype: int64

In [ ]:
df_local_votacao_pb.to_csv(
    '/content/drive/MyDrive/Dissertacao_TSE/eleitorado_local_votacao_2024_PB.csv',
    sep=';',
    encoding='latin1',
    index=False
)

print("Arquivo salvo no Drive!")

Arquivo salvo no Drive!

In [ ]:
import os
print(os.listdir('/content/drive/MyDrive/Dissertacao_TSE/'))

['perfil_eleitor_secao_2024_PB.zip', 'perfil_eleitor_secao_2024_PB.csv', 'perfil_comparecimento_abstencao_2024.zip', 'perfil_comparecimento_abstencao_2024_BRASIL.csv', 'perfil_comparecimento_abstencao_2024_PB.csv', 'leiame.pdf', 'eleitorado_local_votacao_2024_PB.csv', 'perfil_comparecimento_abstencao_2024_AC.csv', 'perfil_comparecimento_abstencao_2024_MT.csv', 'perfil_comparecimento_abstencao_2024_AL.csv', 'perfil_comparecimento_abstencao_2024_BA.csv', 'perfil_comparecimento_abstencao_2024_AM.csv', 'perfil_comparecimento_abstencao_2024_AP.csv', 'perfil_comparecimento_abstencao_2024_PA.csv', 'perfil_comparecimento_abstencao_2024_MS.csv', 'perfil_comparecimento_abstencao_2024_CE.csv', 'perfil_comparecimento_abstencao_2024_ES.csv', 'perfil_comparecimento_abstencao_2024_MA.csv', 'perfil_comparecimento_abstencao_2024_GO.csv', 'perfil_comparecimento_abstencao_2024_MG.csv', 'perfil_comparecimento_abstencao_2024_PE.csv', 'perfil_comparecimento_abstencao_2024_PI.csv', 'perfil_comparecimento_abstencao_2024_PR.csv', 'perfil_comparecimento_abstencao_2024_RJ.csv', 'perfil_comparecimento_abstencao_2024_RN.csv', 'perfil_comparecimento_abstencao_2024_RO.csv', 'perfil_comparecimento_abstencao_2024_RR.csv', 'perfil_comparecimento_abstencao_2024_RS.csv', 'perfil_comparecimento_abstencao_2024_SC.csv', 'perfil_comparecimento_abstencao_2024_SE.csv', 'perfil_comparecimento_abstencao_2024_SP.csv', 'perfil_comparecimento_abstencao_2024_TO.csv']

## 2. Silver — Limpeza e padronização

### 2.1 Padronizar dsGrauEscolaridade (Arquivo 1 vs Arquivo 2)

In [ ]:
df['dsGrauEscolaridade'] = df['DS_GRAU_ESCOLARIDADE']
df_comparecimento['dsGrauEscolaridade'] = df_comparecimento['DS_GRAU_ESCOLARIDADE']

print("Valores em df (Arquivo 1):")
print(df['dsGrauEscolaridade'].unique())

print("\nValores em df_comparecimento (Arquivo 2):")
print(df_comparecimento['dsGrauEscolaridade'].unique())

Valores em df (Arquivo 1):
['ENSINO FUNDAMENTAL INCOMPLETO' 'SUPERIOR INCOMPLETO' 'LÊ E ESCREVE'
 'ANALFABETO' 'ENSINO MÉDIO COMPLETO' 'ENSINO MÉDIO INCOMPLETO'
 'ENSINO FUNDAMENTAL COMPLETO' 'SUPERIOR COMPLETO']

Valores em df_comparecimento (Arquivo 2):
['ENSINO MÉDIO INCOMPLETO' 'ENSINO FUNDAMENTAL COMPLETO'
 'ENSINO MÉDIO COMPLETO' 'ENSINO FUNDAMENTAL INCOMPLETO'
 'SUPERIOR INCOMPLETO' 'LÊ E ESCREVE' 'SUPERIOR COMPLETO' 'ANALFABETO']

In [ ]:
# qtEletoresBiometria é opcional no modelo (nem todo perfil tem biometria cadastrada).
# Verifica quantos registros estão sem essa informação (NaN)
print("Registros sem qtEletoresBiometria:")
print(df['QT_ELEITORES_BIOMETRIA'].isna().sum())

# Verifica se existem linhas duplicadas (mesmo registro repetido)
print("\nLinhas duplicadas em df (Arquivo 1):", df.duplicated().sum())
print("Linhas duplicadas em df_comparecimento (Arquivo 2):", df_comparecimento.duplicated().sum())

Registros sem qtEletoresBiometria:
0

Linhas duplicadas em df (Arquivo 1): 2563
Linhas duplicadas em df_comparecimento (Arquivo 2): 30

In [ ]:
# Remove linhas duplicadas (mantém a primeira ocorrência de cada)
linhas_antes_df = df.shape[0]
df = df.drop_duplicates().reset_index(drop=True)
print(f"Arquivo 1: removidas {linhas_antes_df - df.shape[0]} linhas duplicadas. Total agora: {df.shape[0]}")

linhas_antes_comp = df_comparecimento.shape[0]
df_comparecimento = df_comparecimento.drop_duplicates().reset_index(drop=True)
print(f"Arquivo 2: removidas {linhas_antes_comp - df_comparecimento.shape[0]} linhas duplicadas. Total agora: {df_comparecimento.shape[0]}")

Arquivo 1: removidas 2563 linhas duplicadas. Total agora: 1808156
Arquivo 2: removidas 30 linhas duplicadas. Total agora: 302916

In [ ]:
print("Valores únicos (os primeiros 20):")
print(sorted(df['QT_ELEITORES_BIOMETRIA'].unique())[:20])

print("\nResumo estatístico:")
print(df['QT_ELEITORES_BIOMETRIA'].describe())

# Compara com o total de eleitores do grupo (QT_ELEITORES_PERFIL)
# Se biometria for sempre menor ou igual ao total, é contagem (quantidade), não sim/não
print("\nBiometria é sempre <= total de eleitores do perfil?")
print((df['QT_ELEITORES_BIOMETRIA'] <= df['QT_ELEITORES_PERFIL']).all())

Valores únicos (os primeiros 20):
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]

Resumo estatístico:
count    1.808156e+06
mean     1.688408e+00
std      1.732430e+00
min      0.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      2.000000e+00
max      1.020000e+02
Name: QT_ELEITORES_BIOMETRIA, dtype: float64

Biometria é sempre <= total de eleitores do perfil?
True

## 3. Gold — Construção dos documentos (modelo C2)

### 3.1 Coleção municipios

In [ ]:
# Para cada município, descobrir quais zonas ele tem (vem do Arquivo 1)
# e quais turnos ele teve (vem do Arquivo 2)

zonas_por_municipio = df.groupby('CD_MUNICIPIO')['NR_ZONA'].unique().apply(lambda x: sorted(x.tolist()))
turnos_por_municipio = df_comparecimento.groupby('CD_MUNICIPIO')['NR_TURNO'].unique().apply(lambda x: sorted(x.tolist()))

# Pega nome do município e UF (são fixos, então tanto faz usar o df)
nomes_municipio = df.groupby('CD_MUNICIPIO')['NM_MUNICIPIO'].first()
uf_municipio = df.groupby('CD_MUNICIPIO')['SG_UF'].first()

# Monta a lista de documentos no formato exato da coleção municipios
documentos_municipios = []
for cd_municipio in nomes_municipio.index:
    doc = {
        "_id": int(cd_municipio),
        "nmMunicipio": nomes_municipio[cd_municipio],
        "sgUf": uf_municipio[cd_municipio],
        "turnos": [int(t) for t in turnos_por_municipio.get(cd_municipio, [1])],
        "zonas": [int(z) for z in zonas_por_municipio[cd_municipio]],
    }
    documentos_municipios.append(doc)

print(f"Total de municípios montados: {len(documentos_municipios)}")
print("\nExemplo (primeiro município):")
print(documentos_municipios[0])

Total de municípios montados: 223

Exemplo (primeiro município):
{'_id': 19003, 'nmMunicipio': 'RIACHÃO DO POÇO', 'sgUf': 'PB', 'turnos': [1], 'zonas': [4]}

### 3.2 Coleção zonas

In [ ]:
# Para cada zona, descobrir quais municípios ela abrange (Arquivo 1)
municipios_por_zona = df.groupby('NR_ZONA')['CD_MUNICIPIO'].unique().apply(lambda x: sorted(int(c) for c in x))

documentos_zonas = []
for nr_zona in municipios_por_zona.index:
    doc = {
        "_id": int(nr_zona),
        "nmSede": None,  # placeholder — será enriquecido depois com o PDF do TRE-PB
        "municipios": municipios_por_zona[nr_zona],
    }
    documentos_zonas.append(doc)

print(f"Total de zonas montadas: {len(documentos_zonas)}")
print("\nExemplo (primeira zona):")
print(documentos_zonas[0])

Total de zonas montadas: 68

Exemplo (primeira zona):
{'_id': 1, 'nmSede': None, 'municipios': [20516]}

### 3.2.1 Validação cruzada com conhecimento institucional (TRE-PB)

Confere se a distribuição de municípios por zona bate com o que se sabe sobre o eleitorado da PB: cidades grandes (João Pessoa, Campina Grande, Cabedelo, Bayeux, Guarabira) costumam ocupar uma zona inteira sozinhas, enquanto municípios menores compartilham zona com vizinhos.

In [ ]:
# Quantos municípios cada zona tem? (queremos ver a distribuição)
qtd_municipios_por_zona = {doc["_id"]: len(doc["municipios"]) for doc in documentos_zonas}

print("Quantas zonas têm exatamente 1 município (são grandes demais pra compartilhar):")
zonas_1_municipio = [z for z, qtd in qtd_municipios_por_zona.items() if qtd == 1]
print(len(zonas_1_municipio), "zonas:", zonas_1_municipio)

# Pra cada uma dessas zonas "sozinhas", qual é o nome do município?
print("\nNomes desses municípios:")
for nr_zona in zonas_1_municipio:
    cd_municipio = documentos_zonas[[d["_id"] for d in documentos_zonas].index(nr_zona)]["municipios"][0]
    print(f"Zona {nr_zona} -> {nomes_municipio[cd_municipio]}")

Quantas zonas têm exatamente 1 município (são grandes demais pra compartilhar):
9 zonas: [1, 10, 17, 57, 61, 64, 70, 76, 77]

Nomes desses municípios:
Zona 1 -> JOÃO PESSOA
Zona 10 -> GUARABIRA
Zona 17 -> CAMPINA GRANDE
Zona 57 -> CABEDELO
Zona 61 -> BAYEUX
Zona 64 -> JOÃO PESSOA
Zona 70 -> JOÃO PESSOA
Zona 76 -> JOÃO PESSOA
Zona 77 -> JOÃO PESSOA

In [ ]:
# Descobre o código de Campina Grande
cd_campina_grande = nomes_municipio[nomes_municipio == 'CAMPINA GRANDE'].index[0]
print(f"Código de Campina Grande: {cd_campina_grande}")

# Em quais zonas o código de Campina Grande aparece (sozinho ou compartilhado)?
print("\nZonas que contêm Campina Grande:")
for doc in documentos_zonas:
    if cd_campina_grande in doc["municipios"]:
        nomes_dos_municipios = [nomes_municipio[cd] for cd in doc["municipios"]]
        print(f"Zona {doc['_id']}: {nomes_dos_municipios}")

Código de Campina Grande: 19810

Zonas que contêm Campina Grande:
Zona 16: ['CAMPINA GRANDE', 'MASSARANDUBA']
Zona 17: ['CAMPINA GRANDE']
Zona 72: ['CAMPINA GRANDE', 'SERRA REDONDA']

### 3.2.2 Enriquecimento de nmSede (PDF TRE-PB)

Dicionário construído manualmente a partir do documento oficial do TRE-PB
("Municípios abrangidos pelas Zonas Eleitorais na Paraíba"), mapeando
cada zona ao município-sede (cartório eleitoral responsável).

In [ ]:
# Dicionário zona -> município sede (cartório), extraído do PDF do TRE-PB
mapa_sede = {
    1: "João Pessoa", 2: "Santa Rita", 3: "Santa Rita", 4: "Sapé",
    6: "Itabaiana", 7: "Mamanguape", 8: "Ingá", 9: "Alagoa Grande",
    10: "Guarabira", 11: "Areia", 13: "Alagoa Nova", 14: "Bananeiras",
    16: "Campina Grande", 17: "Campina Grande", 18: "Umbuzeiro", 19: "Esperança",
    20: "Araruna", 22: "Campina Grande", 23: "Soledade", 24: "Cuité",
    25: "Picuí", 26: "Santa Luzia", 27: "Taperoá", 28: "Patos",
    29: "Monteiro", 30: "Teixeira", 31: "Pombal", 32: "Piancó",
    33: "Itaporanga", 34: "Princesa Isabel", 35: "Sousa", 36: "Catolé do Rocha",
    38: "Catolé do Rocha", 40: "São José de Piranhas", 41: "Conceição", 42: "Itaporanga",
    43: "Sumé", 44: "Pedras de Fogo", 47: "Guarabira", 48: "Solânea",
    49: "Queimadas", 50: "Pocinhos", 51: "Patos", 52: "Coremas",
    55: "Rio Tinto", 56: "Juazeirinho", 57: "Cabedelo", 58: "Serra Branca",
    59: "Queimadas", 60: "Jacaraú", 61: "Bayeux", 62: "Boqueirão",
    63: "Sousa", 64: "João Pessoa", 65: "Patos", 66: "Piancó",
    67: "Remígio", 68: "Cajazeiras", 69: "São Bento", 70: "João Pessoa",
    72: "Campina Grande", 73: "Alhandra", 74: "Água Branca", 75: "Gurinhém",
    76: "João Pessoa", 77: "João Pessoa",
    # 37 e 53 ficaram sem cartório identificável no PDF — a confirmar com o TRE-PB
}

# Aplica o mapeamento nos documentos de zonas
for doc in documentos_zonas:
    doc["nmSede"] = mapa_sede.get(doc["_id"])

# Confere se ficou alguma zona sem sede (None)
zonas_sem_sede = [doc["_id"] for doc in documentos_zonas if doc["nmSede"] is None]
print(f"Zonas sem nmSede identificado: {zonas_sem_sede}")

print("\nExemplo (zona 22 — sede em Campina Grande, sem o município no array):")
print([d for d in documentos_zonas if d["_id"] == 22][0])

Zonas sem nmSede identificado: [37, 53]

Exemplo (zona 22 — sede em Campina Grande, sem o município no array):
{'_id': 22, 'nmSede': 'Campina Grande', 'municipios': [19240, 19941, 20311, 21814]}

In [ ]:
mapa_sede[37] = "São João do Rio do Peixe"
mapa_sede[53] = "São João do Rio do Peixe"

# Reaplica nos documentos de zonas
for doc in documentos_zonas:
    doc["nmSede"] = mapa_sede.get(doc["_id"])

# Confere de novo se sobrou alguma zona sem sede
zonas_sem_sede = [doc["_id"] for doc in documentos_zonas if doc["nmSede"] is None]
print(f"Zonas sem nmSede identificado: {zonas_sem_sede}")

Zonas sem nmSede identificado: []

### 3.3 Coleção secoes (junção Arquivo 1 + Arquivo 3)

In [ ]:
# 1. Pega uma linha única por seção (zona+secao), com os dados do local de votação
#    (vem do Arquivo 1 - cada seção aparece várias vezes, uma por perfil demográfico,
#    mas o local de votação é sempre o mesmo, então pegamos só a primeira ocorrência)
secoes_base = df.groupby(['NR_ZONA', 'NR_SECAO']).agg(
    nrLocalVotacao=('NR_LOCAL_VOTACAO', 'first'),
    nmLocalVotacao=('NM_LOCAL_VOTACAO', 'first')
).reset_index()

print(f"Total de seções únicas (Arquivo 1): {secoes_base.shape[0]}")

# 2. Junta com o Arquivo 3, que tem a informação de acessibilidade,
#    usando zona+seção como chave de cruzamento
secoes_com_acessibilidade = secoes_base.merge(
    df_local_votacao_pb[['NR_ZONA', 'NR_SECAO', 'DS_SITU_SECAO_ACESSIBILIDADE']],
    on=['NR_ZONA', 'NR_SECAO'],
    how='left'
)

print(f"Total depois do merge: {secoes_com_acessibilidade.shape[0]}")
print(f"\nSeções SEM informação de acessibilidade encontrada (merge não bateu):")
print(secoes_com_acessibilidade['DS_SITU_SECAO_ACESSIBILIDADE'].isna().sum())

secoes_com_acessibilidade.head()

Total de seções únicas (Arquivo 1): 10626
Total depois do merge: 13234

Seções SEM informação de acessibilidade encontrada (merge não bateu):
0

,NR_ZONA,NR_SECAO,nrLocalVotacao,nmLocalVotacao,DS_SITU_SECAO_ACESSIBILIDADE
0,1,1,1767,FPB - FACULDADE INTERNACIONAL DA PARAÍBA,Com acessibilidade
1,1,1,1767,FPB - FACULDADE INTERNACIONAL DA PARAÍBA,Com acessibilidade
2,1,3,1031,COLEGIO OLIVINA OLIVIA CARNEIRO DA CUNHA,Com acessibilidade
3,1,3,1031,COLEGIO OLIVINA OLIVIA CARNEIRO DA CUNHA,Com acessibilidade
4,1,4,1767,FPB - FACULDADE INTERNACIONAL DA PARAÍBA,Sem acessibilidade

#### 3.3.1 Investigação: duplicação no merge (Arquivo 3 tem 2 turnos)

In [ ]:
# Confirma a hipótese: o Arquivo 3 tem mais de uma linha por zona+secao?
duplicadas_arquivo3 = df_local_votacao_pb.groupby(['NR_ZONA', 'NR_SECAO']).size()
print("Quantas seções têm mais de 1 linha no Arquivo 3:")
print((duplicadas_arquivo3 > 1).sum())

# Se for por causa de NR_TURNO, confirma:
print("\nValores únicos de NR_TURNO no Arquivo 3:")
print(df_local_votacao_pb['NR_TURNO'].value_counts())

Quantas seções têm mais de 1 linha no Arquivo 3:
2610

Valores únicos de NR_TURNO no Arquivo 3:
NR_TURNO
1    10630
2     2610
Name: count, dtype: int64

#### 3.3.2 Investigação: verificação de zona "0" (falso alarme)

In [ ]:
# Investiga a zona 0
print("Quantas linhas têm NR_ZONA = 0 no Arquivo 3:")
print((df_local_votacao_pb['NR_ZONA'] == 0).sum())

print("\nExemplo de linhas com zona 0:")
print(df_local_votacao_pb[df_local_votacao_pb['NR_ZONA'] == 0][['NR_ZONA', 'NR_SECAO', 'NM_MUNICIPIO', 'DS_TIPO_LOCAL', 'DS_SITU_LOCAL_VOTACAO']].head(10))

# Confirma também se a zona 0 existe no Arquivo 1 (perfil_eleitor_secao)
print("\nZona 0 existe no Arquivo 1?")
print((df['NR_ZONA'] == 0).sum())

Quantas linhas têm NR_ZONA = 0 no Arquivo 3:
0

Exemplo de linhas com zona 0:
Empty DataFrame
Columns: [NR_ZONA, NR_SECAO, NM_MUNICIPIO, DS_TIPO_LOCAL, DS_SITU_LOCAL_VOTACAO]
Index: []

Zona 0 existe no Arquivo 1?
0

#### 3.3.3 Correção: filtrar turno 1 antes do merge

In [ ]:
# Filtra só turno 1 (acessibilidade do local é a mesma nos dois turnos)
df_local_votacao_pb_t1 = df_local_votacao_pb[df_local_votacao_pb['NR_TURNO'] == 1].copy()

print(f"Linhas após filtrar turno 1: {df_local_votacao_pb_t1.shape[0]}")

# Refaz o merge, agora sem duplicar
secoes_com_acessibilidade = secoes_base.merge(
    df_local_votacao_pb_t1[['NR_ZONA', 'NR_SECAO', 'DS_SITU_SECAO_ACESSIBILIDADE']],
    on=['NR_ZONA', 'NR_SECAO'],
    how='left'
)

print(f"Total depois do merge corrigido: {secoes_com_acessibilidade.shape[0]}")
print(f"Seções sem acessibilidade encontrada: {secoes_com_acessibilidade['DS_SITU_SECAO_ACESSIBILIDADE'].isna().sum()}")

Linhas após filtrar turno 1: 10630
Total depois do merge corrigido: 10626
Seções sem acessibilidade encontrada: 0

### 3.4 Montagem final dos documentos de secoes

In [ ]:
documentos_secoes = []
for _, row in secoes_com_acessibilidade.iterrows():
    doc = {
        "_id": {"nrZona": int(row['NR_ZONA']), "nrSecao": int(row['NR_SECAO'])},
        "localVotacao": {
            "nrLocalVotacao": int(row['nrLocalVotacao']),
            "nmLocalVotacao": row['nmLocalVotacao'],
            "dsSituAcessibilidade": row['DS_SITU_SECAO_ACESSIBILIDADE'],
        }
    }
    documentos_secoes.append(doc)

print(f"Total de documentos de secoes: {len(documentos_secoes)}")
print("\nExemplo:")
print(documentos_secoes[0])

Total de documentos de secoes: 10626

Exemplo:
{'_id': {'nrZona': 1, 'nrSecao': 1}, 'localVotacao': {'nrLocalVotacao': 1767, 'nmLocalVotacao': 'FPB - FACULDADE INTERNACIONAL DA PARAÍBA', 'dsSituAcessibilidade': 'Com acessibilidade'}}

## 4. Carga — Conexão e inserção no MongoDB Atlas

### 4.1 Conectar ao Atlas

In [1]:
!pip install pymongo --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 9.9 MB/s eta 0:00:00

In [3]:
from pymongo import MongoClient
from getpass import getpass
from urllib.parse import quote_plus

# Pede a senha sem mostrar na tela
senha = getpass("Cole aqui a senha do usuário luciananorat_db_user: ")

# Codifica a senha pra ela funcionar mesmo com caracteres especiais (@, #, etc)
senha_codificada = quote_plus(senha)

uri = f"mongodb+srv://luciananorat_db_user:{senha_codificada}@cluster0.0eiumbm.mongodb.net/?retryWrites=true&w=majority"

cliente = MongoClient(uri)
banco = cliente["eleicoes_pcd_2024"]

print("Bancos de dados disponíveis no cluster:")
print(cliente.list_database_names())

Cole aqui a senha do usuário luciananorat_db_user: ··········
Bancos de dados disponíveis no cluster:
['eleicoes_pcd_2024', 'livraria', 'tre_pb', 'admin', 'local']

### 4.2 Inserir municipios, zonas e secoes

In [ ]:
# Insere os documentos em cada coleção (cria a coleção automaticamente, se não existir)
resultado_municipios = banco["municipios"].insert_many(documentos_municipios)
print(f"municipios: {len(resultado_municipios.inserted_ids)} documentos inseridos")

resultado_zonas = banco["zonas"].insert_many(documentos_zonas)
print(f"zonas: {len(resultado_zonas.inserted_ids)} documentos inseridos")

resultado_secoes = banco["secoes"].insert_many(documentos_secoes)
print(f"secoes: {len(resultado_secoes.inserted_ids)} documentos inseridos")

# Confirma o que existe no banco agora
print("\nColeções criadas no banco eleicoes_pcd_2024:")
print(banco.list_collection_names())

municipios: 223 documentos inseridos
zonas: 68 documentos inseridos
secoes: 10626 documentos inseridos

Coleções criadas no banco eleicoes_pcd_2024:
['secoes', 'municipios', 'zonas']

### 4.2.1 Construção do documento perfis (Gold, antes da carga)

In [ ]:
documentos_perfis = []

for _, row in df.iterrows():
    tipo = "PCD" if row['QT_ELEITORES_DEFICIENCIA'] > 0 else "NAO_PCD"

    doc = {
        "nrZona": int(row['NR_ZONA']),
        "nrSecao": int(row['NR_SECAO']),
        "tipo": tipo,
        "dsGenero": row['DS_GENERO'],
        "dsEstadoCivil": row['DS_ESTADO_CIVIL'],
        "dsFaixaEtaria": row['DS_FAIXA_ETARIA'],
        "dsGrauEscolaridade": row['dsGrauEscolaridade'],
        "dsRacaCor": row['DS_RACA_COR'],
        "qtEletoresAptos": int(row['QT_ELEITORES_PERFIL']),
        "tpObrigatoriedadeVoto": row['TP_OBRIGATORIEDADE_VOTO'],
        "qtEletoresBiometria": int(row['QT_ELEITORES_BIOMETRIA']),
    }

    # Só adiciona qtEletoresDeficiencia se for um perfil PCD
    if tipo == "PCD":
        doc["qtEletoresDeficiencia"] = int(row['QT_ELEITORES_DEFICIENCIA'])

    documentos_perfis.append(doc)

print(f"Total de documentos de perfis: {len(documentos_perfis)}")
print("\nExemplo PCD:")
print(next(d for d in documentos_perfis if d['tipo'] == 'PCD'))
print("\nExemplo NAO_PCD:")
print(next(d for d in documentos_perfis if d['tipo'] == 'NAO_PCD'))

Total de documentos de perfis: 1808156

Exemplo PCD:
{'nrZona': 2, 'nrSecao': 276, 'tipo': 'PCD', 'dsGenero': 'FEMININO', 'dsEstadoCivil': 'SOLTEIRO', 'dsFaixaEtaria': '40 a 44 anos', 'dsGrauEscolaridade': 'ENSINO FUNDAMENTAL INCOMPLETO', 'dsRacaCor': 'NÃO INFORMADO', 'qtEletoresAptos': 10, 'tpObrigatoriedadeVoto': 'Obrigatório', 'qtEletoresBiometria': 10, 'qtEletoresDeficiencia': 1}

Exemplo NAO_PCD:
{'nrZona': 50, 'nrSecao': 15, 'tipo': 'NAO_PCD', 'dsGenero': 'FEMININO', 'dsEstadoCivil': 'CASADO', 'dsFaixaEtaria': '55 a 59 anos', 'dsGrauEscolaridade': 'ENSINO FUNDAMENTAL INCOMPLETO', 'dsRacaCor': 'NÃO INFORMADO', 'qtEletoresAptos': 2, 'tpObrigatoriedadeVoto': 'Obrigatório', 'qtEletoresBiometria': 2}

### 4.2.2 Construção do documento comparecimentoZona (Gold, antes da carga)

In [ ]:
# O Arquivo 2 tem uma linha por zona+turno+perfil demográfico.
# Precisamos somar tudo, agrupando só por zona+turno (perdendo o detalhe demográfico,
# que já não é o propósito dessa coleção)
comparecimento_agrupado = df_comparecimento.groupby(['NR_ZONA', 'NR_TURNO']).agg(
    qtComparecimento=('QT_COMPARECIMENTO', 'sum'),
    qtAbstencao=('QT_ABSTENCAO', 'sum'),
    qtComparecimentoDeficiencia=('QT_COMPARECIMENTO_DEFICIENCIA', 'sum'),
    qtAbstencaoDeficiencia=('QT_ABSTENCAO_DEFICIENCIA', 'sum'),
).reset_index()

documentos_comparecimento = []
for _, row in comparecimento_agrupado.iterrows():
    doc = {
        "_id": {"nrZona": int(row['NR_ZONA']), "nrTurno": int(row['NR_TURNO'])},
        "qtComparecimento": int(row['qtComparecimento']),
        "qtAbstencao": int(row['qtAbstencao']),
        "qtComparecimentoDeficiencia": int(row['qtComparecimentoDeficiencia']),
        "qtAbstencaoDeficiencia": int(row['qtAbstencaoDeficiencia']),
    }
    documentos_comparecimento.append(doc)

print(f"Total de documentos: {len(documentos_comparecimento)}")
print("\nExemplo:")
print(documentos_comparecimento[0])

Total de documentos: 76

Exemplo:
{'_id': {'nrZona': 1, 'nrTurno': 1}, 'qtComparecimento': 85711, 'qtAbstencao': 20642, 'qtComparecimentoDeficiencia': 551, 'qtAbstencaoDeficiencia': 314}

### 4.3 Inserir perfis e comparecimentoZona

In [ ]:
# Quantos documentos de perfis já estão no banco?
qtd_ja_inserida = banco["perfis"].count_documents({})
print(f"Documentos de perfis já no Atlas: {qtd_ja_inserida}")
print(f"Faltam inserir: {len(documentos_perfis) - qtd_ja_inserida}")

# Tamanho médio por documento (estimativa)
status = banco.command("dbStats")
print(f"\nTamanho total de dados no banco: {status['dataSize'] / (1024*1024):.2f} MB")
if qtd_ja_inserida > 0:
    print(f"Tamanho médio por documento de perfis: {(status['dataSize'] / qtd_ja_inserida):.0f} bytes")

Documentos de perfis já no Atlas: 1240000
Faltam inserir: 568156

Tamanho total de dados no banco: 366.31 MB
Tamanho médio por documento de perfis: 310 bytes

In [ ]:
banco["perfis"].drop()
df_amostra = df.groupby('NR_ZONA', group_keys=False).apply(lambda grupo: grupo.sample(frac=0.5, random_state=42))
print(f"Amostra: {df_amostra.shape[0]} linhas de {df.shape[0]} originais ({df_amostra.shape[0]/df.shape[0]*100:.1f}%)")

Amostra: 904077 linhas de 1808156 originais (50.0%)

/tmp/ipykernel_5366/3634296566.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_amostra = df.groupby('NR_ZONA', group_keys=False).apply(lambda grupo: grupo.sample(frac=0.5, random_state=42))

### 4.3.1 Justificativa da amostragem estratificada

A amostra foi sorteada separadamente para cada zona eleitoral (50% das
linhas de cada zona, não 50% do total geral). Essa escolha preserva a
proporção de eleitores PCD por zona, incluindo as zonas dos municípios
mais populosos (João Pessoa, Campina Grande, Cabedelo), que concentram
proporcionalmente mais eleitores com deficiência. Uma amostragem simples
do total geral poderia sub-representar essas zonas por acaso.

In [ ]:
documentos_perfis_amostra = []

for _, row in df_amostra.iterrows():
    tipo = "PCD" if row['QT_ELEITORES_DEFICIENCIA'] > 0 else "NAO_PCD"

    doc = {
        "nrZona": int(row['NR_ZONA']),
        "nrSecao": int(row['NR_SECAO']),
        "tipo": tipo,
        "dsGenero": row['DS_GENERO'],
        "dsEstadoCivil": row['DS_ESTADO_CIVIL'],
        "dsFaixaEtaria": row['DS_FAIXA_ETARIA'],
        "dsGrauEscolaridade": row['dsGrauEscolaridade'],
        "dsRacaCor": row['DS_RACA_COR'],
        "qtEletoresAptos": int(row['QT_ELEITORES_PERFIL']),
        "tpObrigatoriedadeVoto": row['TP_OBRIGATORIEDADE_VOTO'],
        "qtEletoresBiometria": int(row['QT_ELEITORES_BIOMETRIA']),
    }

    if tipo == "PCD":
        doc["qtEletoresDeficiencia"] = int(row['QT_ELEITORES_DEFICIENCIA'])

    documentos_perfis_amostra.append(doc)

print(f"Total de documentos na amostra: {len(documentos_perfis_amostra)}")

Total de documentos na amostra: 904077

#### 4.3.2 Verificação: percentual de PCD mantido por zona (original vs. amostra)

Compara o percentual de eleitores PCD por zona antes e depois da amostragem,
focando nas zonas dos municípios mais populosos. A diferença máxima encontrada
foi de 0,04 pontos percentuais (zona 72), confirmando que a amostragem
estratificada preservou a representatividade da concentração de PCD por zona.

In [ ]:
# Compara o percentual de PCD antes e depois da amostragem
pcd_original = df.groupby('NR_ZONA')['QT_ELEITORES_DEFICIENCIA'].sum()
total_original = df.groupby('NR_ZONA')['QT_ELEITORES_PERFIL'].sum()
percentual_original = (pcd_original / total_original * 100).round(2)

pcd_amostra = df_amostra.groupby('NR_ZONA')['QT_ELEITORES_DEFICIENCIA'].sum()
total_amostra = df_amostra.groupby('NR_ZONA')['QT_ELEITORES_PERFIL'].sum()
percentual_amostra = (pcd_amostra / total_amostra * 100).round(2)

comparacao = pd.DataFrame({
    'percentual_pcd_original': percentual_original,
    'percentual_pcd_amostra': percentual_amostra
})

print("Comparação do percentual de PCD por zona (original vs. amostra):")
print(comparacao.loc[[1, 64, 70, 76, 77, 16, 17, 72, 57]])  # zonas de JP, CG e Cabedelo

Comparação do percentual de PCD por zona (original vs. amostra):
         percentual_pcd_original  percentual_pcd_amostra
NR_ZONA
1                           0.81                    0.81
64                          0.83                    0.82
70                          0.70                    0.71
76                          0.72                    0.71
77                          1.10                    1.12
16                          0.97                    0.96
17                          0.86                    0.87
72                          0.92                    0.96
57                          0.77                    0.74

### 4.4 Inserção final: comparecimentoZona e perfis (amostra)

Conclui a carga das 5 coleções do modelo C2 no MongoDB Atlas:
municipios, zonas, secoes, perfis (amostra estratificada de 50%) e
comparecimentoZona. A partir deste ponto, o banco está pronto para
consulta pela equipe (incluindo a Mônica, via usuário de leitura).

In [ ]:
# Confirma que comparecimentoZona já está completo
qtd_comparecimento = banco["comparecimentoZona"].count_documents({})
print(f"Documentos em comparecimentoZona: {qtd_comparecimento} (esperado: 76)")

# Roda só a inserção de perfis (sem repetir o comparecimentoZona)
tamanho_lote = 10000
total_inserido = 0

for inicio in range(0, len(documentos_perfis_amostra), tamanho_lote):
    lote = documentos_perfis_amostra[inicio:inicio + tamanho_lote]
    banco["perfis"].insert_many(lote)
    total_inserido += len(lote)
    print(f"Inseridos {total_inserido} de {len(documentos_perfis_amostra)}...")

print(f"\nperfis: {total_inserido} documentos inseridos no total")
print("\nColeções no banco agora:")
print(banco.list_collection_names())

Documentos em comparecimentoZona: 76 (esperado: 76)
Inseridos 10000 de 904077...
Inseridos 20000 de 904077...
Inseridos 30000 de 904077...
Inseridos 40000 de 904077...
Inseridos 50000 de 904077...
Inseridos 60000 de 904077...
Inseridos 70000 de 904077...
Inseridos 80000 de 904077...
Inseridos 90000 de 904077...
Inseridos 100000 de 904077...
Inseridos 110000 de 904077...
Inseridos 120000 de 904077...
Inseridos 130000 de 904077...
Inseridos 140000 de 904077...
Inseridos 150000 de 904077...
Inseridos 160000 de 904077...
Inseridos 170000 de 904077...
Inseridos 180000 de 904077...
Inseridos 190000 de 904077...
Inseridos 200000 de 904077...
Inseridos 210000 de 904077...
Inseridos 220000 de 904077...
Inseridos 230000 de 904077...
Inseridos 240000 de 904077...
Inseridos 250000 de 904077...
Inseridos 260000 de 904077...
Inseridos 270000 de 904077...
Inseridos 280000 de 904077...
Inseridos 290000 de 904077...
Inseridos 300000 de 904077...
Inseridos 310000 de 904077...
Inseridos 320000 de 904077...
Inseridos 330000 de 904077...
Inseridos 340000 de 904077...
Inseridos 350000 de 904077...
Inseridos 360000 de 904077...
Inseridos 370000 de 904077...
Inseridos 380000 de 904077...
Inseridos 390000 de 904077...
Inseridos 400000 de 904077...
Inseridos 410000 de 904077...
Inseridos 420000 de 904077...
Inseridos 430000 de 904077...
Inseridos 440000 de 904077...
Inseridos 450000 de 904077...
Inseridos 460000 de 904077...
Inseridos 470000 de 904077...
Inseridos 480000 de 904077...
Inseridos 490000 de 904077...
Inseridos 500000 de 904077...
Inseridos 510000 de 904077...
Inseridos 520000 de 904077...
Inseridos 530000 de 904077...
Inseridos 540000 de 904077...
Inseridos 550000 de 904077...
Inseridos 560000 de 904077...
Inseridos 570000 de 904077...
Inseridos 580000 de 904077...
Inseridos 590000 de 904077...
Inseridos 600000 de 904077...
Inseridos 610000 de 904077...
Inseridos 620000 de 904077...
Inseridos 630000 de 904077...
Inseridos 640000 de 904077...
Inseridos 650000 de 904077...
Inseridos 660000 de 904077...
Inseridos 670000 de 904077...
Inseridos 680000 de 904077...
Inseridos 690000 de 904077...
Inseridos 700000 de 904077...
Inseridos 710000 de 904077...
Inseridos 720000 de 904077...
Inseridos 730000 de 904077...
Inseridos 740000 de 904077...
Inseridos 750000 de 904077...
Inseridos 760000 de 904077...
Inseridos 770000 de 904077...
Inseridos 780000 de 904077...
Inseridos 790000 de 904077...
Inseridos 800000 de 904077...
Inseridos 810000 de 904077...
Inseridos 820000 de 904077...
Inseridos 830000 de 904077...
Inseridos 840000 de 904077...
Inseridos 850000 de 904077...
Inseridos 860000 de 904077...
Inseridos 870000 de 904077...
Inseridos 880000 de 904077...
Inseridos 890000 de 904077...
Inseridos 900000 de 904077...
Inseridos 904077 de 904077...

perfis: 904077 documentos inseridos no total

Coleções no banco agora:
['secoes', 'municipios', 'zonas', 'perfis', 'comparecimentoZona']

## 5. Índices e Desempenho

### 5.1 Antes do índice: explain() na consulta mais frequente

Avaliamos a consulta mais frequente do projeto — buscar perfis PCD de uma
zona específica — sem nenhum índice criado, para medir o custo real de
uma varredura completa da coleção (COLLSCAN).

In [ ]:
# Consulta mais frequente do projeto: perfis PCD de uma zona específica
resultado_antes = banco["perfis"].find(
    {"nrZona": 1, "tipo": "PCD"}
).explain()

print("Estágio de execução (ANTES do índice):")
print(resultado_antes["executionStats"]["executionStages"]["stage"])
print(f"\nDocumentos examinados: {resultado_antes['executionStats']['totalDocsExamined']}")
print(f"Documentos retornados: {resultado_antes['executionStats']['nReturned']}")
print(f"Tempo de execução: {resultado_antes['executionStats']['executionTimeMillis']} ms")

Estágio de execução (ANTES do índice):
COLLSCAN

Documentos examinados: 904077
Documentos retornados: 428
Tempo de execução: 799 ms

### 5.2 Criação do índice (zona + tipo)

Índice composto seguindo a regra ESR (Equality, Sort, Range): ambos os campos
da consulta mais frequente (nrZona, tipo) são de igualdade, então a ordem
entre eles não impacta o desempenho neste caso específico.

### 5.3 Depois do índice: explain() na mesma consulta

Repetimos exatamente a mesma consulta, agora com o índice
`{nrZona, tipo}` disponível, para comparar o plano de execução
escolhido pelo MongoDB e quantificar o ganho de performance.

In [ ]:
# Cria o índice composto
banco["perfis"].create_index([("nrZona", 1), ("tipo", 1)])
print("Índice criado!")

# Roda a MESMA consulta de novo
resultado_depois = banco["perfis"].find(
    {"nrZona": 1, "tipo": "PCD"}
).explain()

print("\nEstágio de execução (DEPOIS do índice):")
print(resultado_depois["executionStats"]["executionStages"]["stage"])
print(f"\nDocumentos examinados: {resultado_depois['executionStats']['totalDocsExamined']}")
print(f"Documentos retornados: {resultado_depois['executionStats']['nReturned']}")
print(f"Tempo de execução: {resultado_depois['executionStats']['executionTimeMillis']} ms")

Índice criado!

Estágio de execução (DEPOIS do índice):
FETCH

Documentos examinados: 428
Documentos retornados: 428
Tempo de execução: 3 ms

In [ ]:
print("Sub-estágio (onde o IXSCAN realmente aparece):")
print(resultado_depois["executionStats"]["executionStages"]["inputStage"]["stage"])
print("\nNome do índice usado:")
print(resultado_depois["executionStats"]["executionStages"]["inputStage"]["indexName"])

Sub-estágio (onde o IXSCAN realmente aparece):
IXSCAN

Nome do índice usado:
nrZona_1_tipo_1

## 6. Consultas

### 6.1 Find com filtro e projeção

Consulta simples combinando filtro (`$find`) e projeção: retorna apenas
os campos relevantes (gênero, quantidade) dos perfis PCD da zona 1,
em vez do documento completo.

In [ ]:
# Pergunta: "Quais são os perfis PCD da zona 1, mostrando só gênero e quantidade?"
cursor = banco["perfis"].find(
    {"nrZona": 1, "tipo": "PCD"},          # filtro
    {"_id": 0, "dsGenero": 1, "qtEletoresAptos": 1, "qtEletoresDeficiencia": 1}  # projeção
).limit(5)

print("Exemplo de resultado (5 primeiros):")
for doc in cursor:
    print(doc)

Exemplo de resultado (5 primeiros):
{'dsGenero': 'FEMININO', 'qtEletoresAptos': 1, 'qtEletoresDeficiencia': 1}
{'dsGenero': 'MASCULINO', 'qtEletoresAptos': 1, 'qtEletoresDeficiencia': 1}
{'dsGenero': 'FEMININO', 'qtEletoresAptos': 6, 'qtEletoresDeficiencia': 1}
{'dsGenero': 'FEMININO', 'qtEletoresAptos': 1, 'qtEletoresDeficiencia': 1}
{'dsGenero': 'MASCULINO', 'qtEletoresAptos': 2, 'qtEletoresDeficiencia': 1}



### 6.2 Acesso a estruturas embutidas (dot notation)

Demonstra o acesso a um campo dentro de um objeto embutido
(`localVotacao`) usando a notação de ponto — recurso característico
de bancos de documentos como o MongoDB.

In [ ]:
# Pergunta: "Quais seções têm local de votação SEM acessibilidade?"
# localVotacao é um objeto embutido — acessamos o campo interno com "ponto"
cursor = banco["secoes"].find(
    {"localVotacao.dsSituAcessibilidade": "Sem acessibilidade"},
    {"_id": 1, "localVotacao": 1}
).limit(5)

print("Exemplo de seções sem acessibilidade:")
for doc in cursor:
    print(doc)

# Conta o total
total_sem_acesso = banco["secoes"].count_documents(
    {"localVotacao.dsSituAcessibilidade": "Sem acessibilidade"}
)
print(f"\nTotal de seções sem acessibilidade: {total_sem_acesso}")

Exemplo de seções sem acessibilidade:
{'_id': {'nrZona': 1, 'nrSecao': 4}, 'localVotacao': {'nrLocalVotacao': 1767, 'nmLocalVotacao': 'FPB - FACULDADE INTERNACIONAL DA PARAÍBA', 'dsSituAcessibilidade': 'Sem acessibilidade'}}
{'_id': {'nrZona': 1, 'nrSecao': 5}, 'localVotacao': {'nrLocalVotacao': 1767, 'nmLocalVotacao': 'FPB - FACULDADE INTERNACIONAL DA PARAÍBA', 'dsSituAcessibilidade': 'Sem acessibilidade'}}
{'_id': {'nrZona': 1, 'nrSecao': 6}, 'localVotacao': {'nrLocalVotacao': 1767, 'nmLocalVotacao': 'FPB - FACULDADE INTERNACIONAL DA PARAÍBA', 'dsSituAcessibilidade': 'Sem acessibilidade'}}
{'_id': {'nrZona': 1, 'nrSecao': 7}, 'localVotacao': {'nrLocalVotacao': 1767, 'nmLocalVotacao': 'FPB - FACULDADE INTERNACIONAL DA PARAÍBA', 'dsSituAcessibilidade': 'Sem acessibilidade'}}
{'_id': {'nrZona': 1, 'nrSecao': 11}, 'localVotacao': {'nrLocalVotacao': 1066, 'nmLocalVotacao': 'FACULDADE DE DIREITO', 'dsSituAcessibilidade': 'Sem acessibilidade'}}

Total de seções sem acessibilidade: 5559

### 6.3 Acesso a arrays com $elemMatch

Consulta municípios cujo array `zonas` contém algum valor dentro de uma
faixa numérica (60 a 80), usando o operador `$elemMatch` para condições
sobre elementos de um array.

In [ ]:
# Pergunta: "Quais municípios têm alguma zona numerada entre 60 e 80?"
# (As zonas de João Pessoa e Cabedelo, por exemplo, estão nessa faixa)
cursor = banco["municipios"].find(
    {"zonas": {"$elemMatch": {"$gte": 60, "$lte": 80}}},
    {"_id": 0, "nmMunicipio": 1, "zonas": 1}
)

print("Municípios com zona entre 60 e 80:")
for doc in cursor:
    print(doc)

Municípios com zona entre 60 e 80:
{'nmMunicipio': 'ÁGUA BRANCA', 'zonas': [74]}
{'nmMunicipio': 'AGUIAR', 'zonas': [66]}
{'nmMunicipio': 'CURRAL DE CIMA', 'zonas': [60]}
{'nmMunicipio': 'ALHANDRA', 'zonas': [73]}
{'nmMunicipio': 'SÃO DOMINGOS DO CARIRI', 'zonas': [62]}
{'nmMunicipio': 'BARRA DE SANTA ROSA', 'zonas': [67]}
{'nmMunicipio': 'BARRA DE SÃO MIGUEL', 'zonas': [62]}
{'nmMunicipio': 'BAYEUX', 'zonas': [61]}
{'nmMunicipio': 'BOM JESUS', 'zonas': [68]}
{'nmMunicipio': 'BOQUEIRÃO', 'zonas': [62]}
{'nmMunicipio': 'IGARACY', 'zonas': [66]}
{'nmMunicipio': 'CAAPORÃ', 'zonas': [73]}
{'nmMunicipio': 'CABACEIRAS', 'zonas': [62]}
{'nmMunicipio': 'CACHOEIRA DOS ÍNDIOS', 'zonas': [68]}
{'nmMunicipio': 'CACIMBA DE AREIA', 'zonas': [65]}
{'nmMunicipio': 'PEDRO RÉGIS', 'zonas': [60]}
{'nmMunicipio': 'CAJAZEIRAS', 'zonas': [68]}
{'nmMunicipio': 'CALDAS BRANDÃO', 'zonas': [75]}
{'nmMunicipio': 'CAMPINA GRANDE', 'zonas': [16, 17, 72]}
{'nmMunicipio': 'RIACHO DE SANTO ANTÔNIO', 'zonas': [62]}
{'nmMunicipio': 'APARECIDA', 'zonas': [63]}
{'nmMunicipio': 'SÃO FRANCISCO', 'zonas': [63]}
{'nmMunicipio': 'AREIA DE BARAÚNAS', 'zonas': [65]}
{'nmMunicipio': 'ALGODÃO DE JANDAÍRA', 'zonas': [67]}
{'nmMunicipio': 'GURINHÉM', 'zonas': [75]}
{'nmMunicipio': 'IMACULADA', 'zonas': [74]}
{'nmMunicipio': 'ITAPOROROCA', 'zonas': [60]}
{'nmMunicipio': 'JACARAÚ', 'zonas': [60]}
{'nmMunicipio': 'JOÃO PESSOA', 'zonas': [1, 64, 70, 76, 77]}
{'nmMunicipio': 'JURU', 'zonas': [74]}
{'nmMunicipio': 'LAGOA DE DENTRO', 'zonas': [60]}
{'nmMunicipio': 'LASTRO', 'zonas': [63]}
{'nmMunicipio': 'MULUNGU', 'zonas': [75]}
{'nmMunicipio': 'NAZAREZINHO', 'zonas': [63]}
{'nmMunicipio': "OLHO D'ÁGUA", 'zonas': [66]}
{'nmMunicipio': 'PASSAGEM', 'zonas': [65]}
{'nmMunicipio': 'PAULISTA', 'zonas': [69]}
{'nmMunicipio': 'PITIMBU', 'zonas': [73]}
{'nmMunicipio': 'REMÍGIO', 'zonas': [67]}
{'nmMunicipio': 'SALGADINHO', 'zonas': [65]}
{'nmMunicipio': 'SANTA CRUZ', 'zonas': [63]}
{'nmMunicipio': 'SANTANA DOS GARROTES', 'zonas': [66]}
{'nmMunicipio': 'SANTA TERESINHA', 'zonas': [65]}
{'nmMunicipio': 'SÃO BENTO', 'zonas': [69]}
{'nmMunicipio': 'SÃO JOSÉ DO BONFIM', 'zonas': [65]}
{'nmMunicipio': 'SERRA REDONDA', 'zonas': [72]}

### 6.4 Aggregation pipeline — concentração de PCD por zona

Pipeline de agregação que calcula, para cada zona eleitoral, o
percentual de eleitores PCD em relação ao total, usando os estágios
$match, $group, $project e $sort.

In [ ]:
pipeline = [
    {"$match": {"tipo": {"$in": ["PCD", "NAO_PCD"]}}},  # garante que considera todos os perfis
    {"$group": {
        "_id": "$nrZona",
        "totalEleitores": {"$sum": "$qtEletoresAptos"},
        "totalPCD": {"$sum": {
            "$cond": [{"$eq": ["$tipo", "PCD"]}, "$qtEletoresAptos", 0]
        }}
    }},
    {"$project": {
        "_id": 0,
        "nrZona": "$_id",
        "totalEleitores": 1,
        "totalPCD": 1,
        "percentualPCD": {
            "$round": [{"$multiply": [{"$divide": ["$totalPCD", "$totalEleitores"]}, 100]}, 2]
        }
    }},
    {"$sort": {"percentualPCD": -1}},
    {"$limit": 10}
]

resultado = list(banco["perfis"].aggregate(pipeline))

print("Top 10 zonas por percentual de eleitores PCD:")
for doc in resultado:
    print(doc)

Top 10 zonas por percentual de eleitores PCD:
{'totalEleitores': 61837, 'totalPCD': 1808, 'nrZona': 77, 'percentualPCD': 2.92}
{'totalEleitores': 13181, 'totalPCD': 366, 'nrZona': 74, 'percentualPCD': 2.78}
{'totalEleitores': 12052, 'totalPCD': 308, 'nrZona': 52, 'percentualPCD': 2.56}
{'totalEleitores': 54777, 'totalPCD': 1256, 'nrZona': 72, 'percentualPCD': 2.29}
{'totalEleitores': 16093, 'totalPCD': 355, 'nrZona': 49, 'percentualPCD': 2.21}
{'totalEleitores': 15182, 'totalPCD': 330, 'nrZona': 40, 'percentualPCD': 2.17}
{'totalEleitores': 60742, 'totalPCD': 1315, 'nrZona': 17, 'percentualPCD': 2.16}
{'totalEleitores': 58613, 'totalPCD': 1234, 'nrZona': 76, 'percentualPCD': 2.11}
{'totalEleitores': 25828, 'totalPCD': 543, 'nrZona': 44, 'percentualPCD': 2.1}
{'totalEleitores': 14936, 'totalPCD': 306, 'nrZona': 43, 'percentualPCD': 2.05}

### 6.5 $lookup — concentração de PCD × taxa de abstenção por zona

Pipeline que combina dados de duas coleções (`perfis` e
`comparecimentoZona`) usando `$lookup`, relacionando o percentual de
eleitores PCD por zona com a respectiva taxa de abstenção no turno 1.

In [ ]:
pipeline_lookup = [
    {"$group": {
        "_id": "$nrZona",
        "totalEleitores": {"$sum": "$qtEletoresAptos"},
        "totalPCD": {"$sum": {
            "$cond": [{"$eq": ["$tipo", "PCD"]}, "$qtEletoresAptos", 0]
        }}
    }},
    {"$project": {
        "_id": 0,
        "nrZona": "$_id",
        "percentualPCD": {
            "$round": [{"$multiply": [{"$divide": ["$totalPCD", "$totalEleitores"]}, 100]}, 2]
        }
    }},
    # $lookup: busca, para cada zona, o documento correspondente em comparecimentoZona (turno 1)
    {"$lookup": {
        "from": "comparecimentoZona",
        "let": {"zona": "$nrZona"},
        "pipeline": [
            {"$match": {
                "$expr": {
                    "$and": [
                        {"$eq": ["$_id.nrZona", "$$zona"]},
                        {"$eq": ["$_id.nrTurno", 1]}
                    ]
                }
            }}
        ],
        "as": "comparecimento"
    }},
    {"$unwind": "$comparecimento"},
    {"$project": {
        "nrZona": 1,
        "percentualPCD": 1,
        "percentualAbstencao": {
            "$round": [{"$multiply": [
                {"$divide": ["$comparecimento.qtAbstencao",
                    {"$add": ["$comparecimento.qtComparecimento", "$comparecimento.qtAbstencao"]}]},
                100
            ]}, 2]
        }
    }},
    {"$sort": {"percentualPCD": -1}},
    {"$limit": 10}
]

resultado_lookup = list(banco["perfis"].aggregate(pipeline_lookup))

print("Top 10 zonas (PCD% vs Abstenção%):")
for doc in resultado_lookup:
    print(doc)

Top 10 zonas (PCD% vs Abstenção%):
{'nrZona': 77, 'percentualPCD': 2.92, 'percentualAbstencao': 17.78}
{'nrZona': 74, 'percentualPCD': 2.78, 'percentualAbstencao': 17.72}
{'nrZona': 52, 'percentualPCD': 2.56, 'percentualAbstencao': 13.23}
{'nrZona': 72, 'percentualPCD': 2.29, 'percentualAbstencao': 15.09}
{'nrZona': 49, 'percentualPCD': 2.21, 'percentualAbstencao': 13.96}
{'nrZona': 40, 'percentualPCD': 2.17, 'percentualAbstencao': 14.99}
{'nrZona': 17, 'percentualPCD': 2.16, 'percentualAbstencao': 15.74}
{'nrZona': 76, 'percentualPCD': 2.11, 'percentualAbstencao': 23.41}
{'nrZona': 44, 'percentualPCD': 2.1, 'percentualAbstencao': 13.41}
{'nrZona': 43, 'percentualPCD': 2.05, 'percentualAbstencao': 13.23}

### 6.6 Investigação de lentidão — tabela locais_votacao do dashboard

A partir daqui, reproduzimos no Colab a mesma pipeline usada pela tabela
`locais_votacao` do dashboard, para diagnosticar e corrigir o problema de
performance relatado por Mônica. Detalhamento completo da investigação
e dos resultados em `docs/Otimizacao_Indice_Perfis_Dashboard.md`.

In [14]:
# Reaproveitando a conexão "banco" que já existe na sessão

pipeline_tabela = [
    {"$match": {"tipo": "PCD"}},
    {"$group": {
        "_id": {"nrZona": "$nrZona", "nrSecao": "$nrSecao"},
        "totalPCD": {"$sum": 1}
    }},
    {"$sort": {"_id.nrZona": 1, "_id.nrSecao": 1}},
    {"$limit": 50}
]

explicacao = banco.command(
    "explain",
    {
        "aggregate": "perfis",
        "pipeline": pipeline_tabela,
        "cursor": {}
    },
    verbosity="executionStats"
)

import pprint
pprint.pprint(explicacao)

{'$clusterTime': {'clusterTime': Timestamp(1782598447, 1),
                  'signature': {'hash': b'\x9c\xfcG;e\xc1w3\xf8\xba\xb3\x06'
                                        b'\xde/\x81\xe1&\xa6\x84\xf7',
                                'keyId': 7623419680266387459}},
 'command': {'$db': 'eleicoes_pcd_2024',
             'aggregate': 'perfis',
             'cursor': {},
             'pipeline': [{'$match': {'tipo': 'PCD'}},
                          {'$group': {'_id': {'nrSecao': '$nrSecao',
                                              'nrZona': '$nrZona'},
                                      'totalPCD': {'$sum': 1}}},
                          {'$sort': {'_id.nrSecao': 1, '_id.nrZona': 1}},
                          {'$limit': 50}]},
 'explainVersion': '2',
 'ok': 1.0,
 'operationTime': Timestamp(1782598447, 1),
 'queryShapeHash': 'EB3D2E6C7160F5D21EA95037AB7CAE1D321C294481224F9C420A210BF2C119F9',
 'serverInfo': {'gitVersion': 'b19191cc9f5587bb41616283b0a4ca0b3ae522ae',
                'host': 'ac-7ocnihf-shard-00-02.0eiumbm.mongodb.net',
                'port': 27017,
                'version': '8.0.24-patch-6a3992052eafe5000797a34e'},
 'serverParameters': {'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
                      'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
                      'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
                      'internalQueryFacetBufferSizeBytes': 104857600,
                      'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
                      'internalQueryFrameworkControl': 'trySbeRestricted',
                      'internalQueryMaxAddToSetBytes': 104857600,
                      'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
                      'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1,
                      'internalQueryProhibitBlockingMergeOnMongoS': 0},
 'stages': [{'$cursor': {'executionStats': {'executionStages': {'closes': 1,
                                                                'executionTimeMillisEstimate': 11,
                                                                'inputStage': {'closes': 1,
                                                                               'executionTimeMillisEstimate': 10,
                                                                               'inputStage': {'closes': 1,
                                                                                              'executionTimeMillisEstimate': 9,
                                                                                              'expressions': {'5': 'count() ',
                                                                                                              'initExprs': {'5': None}},
                                                                                              'groupBySlots': [1,
                                                                                                               2],
                                                                                              'inputStage': {'closes': 1,
                                                                                                             'executionTimeMillisEstimate': 3,
                                                                                                             'indexKeysToInclude': '00000000000000000000000000000110',
                                                                                                             'indexName': 'tipo_1_nrZona_1_nrSecao_1',
                                                                                                             'isEOF': 1,
                                                                                                             'keysExamined': 12032,
                                                                                                             'nReturned': 12032,
                                                                                                             'numReads': 12033,
                                                                                                             'opens': 1,
                                                                                                             'outputSlots': [1,
                                                                                                                             2],
                                                                                                             'planNodeId': 1,
                                                                                                             'recordIdSlot': 3,
                                                                                                             'restoreState': 9,
                                                                                                             'saveState': 9,
                                                                                                             'seekKeyHigh': 'KS(3C50434400F0F0FE04) ',
                                                                                                             'seekKeyLow': 'KS(3C504344000A0A0104) ',
                                                                                                             'seeks': 1,
                                                                                                             'stage': 'ixseek'},
                                                                                              'isEOF': 1,
                                                                                              'mergingExprs': {'4': 'sum(s4) '},
                                                                                              'nReturned': 6515,
                                                                                              'opens': 1,
                                                                                              'planNodeId': 3,
                                                                                              'restoreState': 9,
                                                                                              'saveState': 9,
                                                                                              'spilledBytes': 0,
                                                                                              'spilledDataStorageSize': 0,
                                                                                              'spilledRecords': 0,
                                                                                              'spills': 0,
                                                                                              'stage': 'group',
                                                                                              'usedDisk': False},
                                                                               'isEOF': 1,
                                                                               'nReturned': 6515,
                                                                               'opens': 1,
                                                                               'planNodeId': 3,
                                                                               'projections': {'6': 'newObj("nrZona", '
                                                                                                    's1, '
                                                                                                    '"nrSecao", '
                                                                                                    's2) ',
                                                                                               '7': '(convert '
                                                                                                    '( '
                                                                                                    's5, '
                                                                                                    'int32) '
                                                                                                    '?: '
                                                                                                    's5) '},
                                                                               'restoreState': 9,
                                                                               'saveState': 9,
                                                                               'stage': 'project'},
                                                                'isEOF': 1,
                                                                'nReturned': 6515,
                                                                'opens': 1,
                                                                'planNodeId': 3,
                                                                'projections': {'8': 'newObj("_id", '
                                                                                     's6, '
                                                                                     '"totalPCD", '
                                                                                     's7) '},
                                                                'restoreState': 9,
                                                                'saveState': 9,
                                                                'stage': 'project'},
                                            'executionSuccess': True,
                                            'executionTimeMillis': 24,
                                            'nReturned': 6515,
                                            'totalDocsExamined': 0,
                                            'totalKeysExamined': 12032},
                         'queryPlanner': {'indexFilterSet': False,
                                          'maxIndexedAndSolutionsReached': False,
                                          'maxIndexedOrSolutionsReached': False,
                                          'maxScansToExplodeReached': False,
                                          'namespace': 'eleicoes_pcd_2024.perfis',
                                          'optimizationTimeMillis': 0,
                                          'parsedQuery': {'tipo': {'$eq': 'PCD'}},
                                          'planCacheKey': 'C78E6493',
                                          'planCacheShapeHash': 'D0E16277',
                                          'prunedSimilarIndexes': False,
                                          'queryHash': 'D0E16277',
                                          'rejectedPlans': [{'inputStage': {'inputStage': {'direction': 'forward',
                                                                                           'indexBounds': {'tipo': ['["PCD", '
                                                                                                                    '"PCD"]']},
                                                                                           'indexName': 'tipo_1',
                                                                                           'indexVersion': 2,
                                                                                           'isMultiKey': False,
                                                                                           'isPartial': False,
                                                                                           'isSparse': False,
                                                                                           'isUnique': False,
                                                                                           'keyPattern': {'tipo': 1},
                                                                                           'multiKeyPaths': {'tipo': []},
                                                                                           'stage': 'IXSCAN'},
                                                                            'stage': 'FETCH'},
                                                             'isCached': False,
                                                             'stage': 'PROJECTION_SIMPLE',
                                                             'transformBy': {'_id': 0,
                                                                             'nrSecao': 1,
                                                                             'nrZona': 1}}],
                                          'winningPlan': {'isCached': False,
                                                          'queryPlan': {'inputStage': {'inputStage': {'direction': 'forward',
                                                                                                      'indexBounds': {'nrSecao': ['[MinKey, '
                                                                                                                                  'MaxKey]'],
                                                                                                                      'nrZona': ['[MinKey, '
                                                                                                                                 'MaxKey]'],
                                                                                                                      'tipo': ['["PCD", '
                                                                                                                               '"PCD"]']},
                                                                                                      'indexName': 'tipo_1_nrZona_1_nrSecao_1',
                                                                                                      'indexVersion': 2,
                                                                                                      'isMultiKey': False,
                                                                                                      'isPartial': False,
                                                                                                      'isSparse': False,
                                                                                                      'isUnique': False,
                                                                                                      'keyPattern': {'nrSecao': 1,
                                                                                                                     'nrZona': 1,
                                                                                                                     'tipo': 1},
                                                                                                      'multiKeyPaths': {'nrSecao': [],
                                                                                                                        'nrZona': [],
                                                                                                                        'tipo': []},
                                                                                                      'planNodeId': 1,
                                                                                                      'stage': 'IXSCAN'},
                                                                                       'planNodeId': 2,
                                                                                       'stage': 'PROJECTION_COVERED',
                                                                                       'transformBy': {'_id': False,
                                                                                                       'nrSecao': True,
                                                                                                       'nrZona': True}},
                                                                        'planNodeId': 3,
                                                                        'stage': 'GROUP'},
                                                          'slotBasedPlan': {'slots': '$$RESULT=s8 '
                                                                                     'env: '
                                                                                     '{  '
                                                                                     '}',
                                                                            'stages': '[3] '
                                                                                      'project '
                                                                                      '[s8 '
                                                                                      '= '
                                                                                      'newObj("_id", '
                                                                                      's6, '
                                                                                      '"totalPCD", '
                                                                                      's7)] \n'
                                                                                      '[3] '
                                                                                      'project '
                                                                                      '[s6 '
                                                                                      '= '
                                                                                      'newObj("nrZona", '
                                                                                      's1, '
                                                                                      '"nrSecao", '
                                                                                      's2), '
                                                                                      's7 '
                                                                                      '= '
                                                                                      '(convert '
                                                                                      '( '
                                                                                      's5, '
                                                                                      'int32) '
                                                                                      '?: '
                                                                                      's5)] \n'
                                                                                      '[3] '
                                                                                      'group '
                                                                                      '[s1, '
                                                                                      's2] '
                                                                                      '[s5 '
                                                                                      '= '
                                                                                      'count()] '
                                                                                      'spillSlots[s4] '
                                                                                      'mergingExprs[sum(s4)] \n'

In [15]:
# Criando o índice em 'tipo' na coleção 'perfis'
colecao_perfis = banco["perfis"]

resultado_indice = colecao_perfis.create_index("tipo")

print("Índice criado com sucesso!")
print("Nome do índice:", resultado_indice)

Índice criado com sucesso!
Nome do índice: tipo_1

In [16]:
# Roda o explain() de novo, agora com o índice tipo_1 já criado
resultado_explain = banco.command(
    "explain",
    {"aggregate": "perfis", "pipeline": pipeline_tabela, "cursor": {}},
    verbosity="executionStats"
)

print(resultado_explain.keys())

import json
print(json.dumps(resultado_explain["stages"][0], indent=2, default=str))

dict_keys(['explainVersion', 'stages', 'queryShapeHash', 'serverInfo', 'serverParameters', 'command', 'ok', '$clusterTime', 'operationTime'])
{
  "$cursor": {
    "queryPlanner": {
      "namespace": "eleicoes_pcd_2024.perfis",
      "parsedQuery": {
        "tipo": {
          "$eq": "PCD"
        }
      },
      "indexFilterSet": false,
      "queryHash": "D0E16277",
      "planCacheShapeHash": "D0E16277",
      "planCacheKey": "C78E6493",
      "optimizationTimeMillis": 0,
      "maxIndexedOrSolutionsReached": false,
      "maxIndexedAndSolutionsReached": false,
      "maxScansToExplodeReached": false,
      "prunedSimilarIndexes": false,
      "winningPlan": {
        "isCached": false,
        "queryPlan": {
          "stage": "GROUP",
          "planNodeId": 3,
          "inputStage": {
            "stage": "PROJECTION_COVERED",
            "planNodeId": 2,
            "transformBy": {
              "nrSecao": true,
              "nrZona": true,
              "_id": false
            },
            "inputStage": {
              "stage": "IXSCAN",
              "planNodeId": 1,
              "keyPattern": {
                "tipo": 1,
                "nrZona": 1,
                "nrSecao": 1
              },
              "indexName": "tipo_1_nrZona_1_nrSecao_1",
              "isMultiKey": false,
              "multiKeyPaths": {
                "tipo": [],
                "nrZona": [],
                "nrSecao": []
              },
              "isUnique": false,
              "isSparse": false,
              "isPartial": false,
              "indexVersion": 2,
              "direction": "forward",
              "indexBounds": {
                "tipo": [
                  "[\"PCD\", \"PCD\"]"
                ],
                "nrZona": [
                  "[MinKey, MaxKey]"
                ],
                "nrSecao": [
                  "[MinKey, MaxKey]"
                ]
              }
            }
          }
        },
        "slotBasedPlan": {
          "slots": "$$RESULT=s8 env: {  }",
          "stages": "[3] project [s8 = newObj(\"_id\", s6, \"totalPCD\", s7)] \n[3] project [s6 = newObj(\"nrZona\", s1, \"nrSecao\", s2), s7 = (convert ( s5, int32) ?: s5)] \n[3] group [s1, s2] [s5 = count()] spillSlots[s4] mergingExprs[sum(s4)] \n[1] ixseek KS(3C504344000A0A0104) KS(3C50434400F0F0FE04) none s3 none none [s1 = 1, s2 = 2] @\"56b360ae-f3dd-4079-8b56-3ef241acf976\" @\"tipo_1_nrZona_1_nrSecao_1\" true "
        }
      },
      "rejectedPlans": [
        {
          "isCached": false,
          "stage": "PROJECTION_SIMPLE",
          "transformBy": {
            "nrSecao": 1,
            "nrZona": 1,
            "_id": 0
          },
          "inputStage": {
            "stage": "FETCH",
            "inputStage": {
              "stage": "IXSCAN",
              "keyPattern": {
                "tipo": 1
              },
              "indexName": "tipo_1",
              "isMultiKey": false,
              "multiKeyPaths": {
                "tipo": []
              },
              "isUnique": false,
              "isSparse": false,
              "isPartial": false,
              "indexVersion": 2,
              "direction": "forward",
              "indexBounds": {
                "tipo": [
                  "[\"PCD\", \"PCD\"]"
                ]
              }
            }
          }
        }
      ]
    },
    "executionStats": {
      "executionSuccess": true,
      "nReturned": 6515,
      "executionTimeMillis": 22,
      "totalKeysExamined": 12032,
      "totalDocsExamined": 0,
      "executionStages": {
        "stage": "project",
        "planNodeId": 3,
        "nReturned": 6515,
        "executionTimeMillisEstimate": 3,
        "opens": 1,
        "closes": 1,
        "saveState": 9,
        "restoreState": 9,
        "isEOF": 1,
        "projections": {
          "8": "newObj(\"_id\", s6, \"totalPCD\", s7) "
        },
        "inputStage": {
          "stage": "project",
          "planNodeId": 3,
          "nReturned": 6515,
          "executionTimeMillisEstimate": 3,
          "opens": 1,
          "closes": 1,
          "saveState": 9,
          "restoreState": 9,
          "isEOF": 1,
          "projections": {
            "6": "newObj(\"nrZona\", s1, \"nrSecao\", s2) ",
            "7": "(convert ( s5, int32) ?: s5) "
          },
          "inputStage": {
            "stage": "group",
            "planNodeId": 3,
            "nReturned": 6515,
            "executionTimeMillisEstimate": 3,
            "opens": 1,
            "closes": 1,
            "saveState": 9,
            "restoreState": 9,
            "isEOF": 1,
            "groupBySlots": [
              1,
              2
            ],
            "expressions": {
              "5": "count() ",
              "initExprs": {
                "5": null
              }
            },
            "mergingExprs": {
              "4": "sum(s4) "
            },
            "usedDisk": false,
            "spills": 0,
            "spilledBytes": 0,
            "spilledRecords": 0,
            "spilledDataStorageSize": 0,
            "inputStage": {
              "stage": "ixseek",
              "planNodeId": 1,
              "nReturned": 12032,
              "executionTimeMillisEstimate": 0,
              "opens": 1,
              "closes": 1,
              "saveState": 9,
              "restoreState": 9,
              "isEOF": 1,
              "indexName": "tipo_1_nrZona_1_nrSecao_1",
              "keysExamined": 12032,
              "seeks": 1,
              "numReads": 12033,
              "recordIdSlot": 3,
              "outputSlots": [
                1,
                2
              ],
              "indexKeysToInclude": "00000000000000000000000000000110",
              "seekKeyLow": "KS(3C504344000A0A0104) ",
              "seekKeyHigh": "KS(3C50434400F0F0FE04) "
            }
          }
        }
      }
    }
  },
  "nReturned": 6515,
  "executionTimeMillisEstimate": 20
}

In [17]:
# Criando o índice composto {tipo, nrZona, nrSecao} na coleção 'perfis'
colecao_perfis = banco["perfis"]

resultado_indice_composto = colecao_perfis.create_index(
    [("tipo", 1), ("nrZona", 1), ("nrSecao", 1)]
)

print("Índice composto criado com sucesso!")
print("Nome do índice:", resultado_indice_composto)

Índice composto criado com sucesso!
Nome do índice: tipo_1_nrZona_1_nrSecao_1

In [18]:
# Mesma pipeline da tabela, agora com o índice composto disponível
resultado_explain_composto = banco.command(
    "explain",
    {"aggregate": "perfis", "pipeline": pipeline_tabela, "cursor": {}},
    verbosity="executionStats"
)

import json
print(json.dumps(resultado_explain_composto["stages"][0], indent=2, default=str))

{
  "$cursor": {
    "queryPlanner": {
      "namespace": "eleicoes_pcd_2024.perfis",
      "parsedQuery": {
        "tipo": {
          "$eq": "PCD"
        }
      },
      "indexFilterSet": false,
      "queryHash": "D0E16277",
      "planCacheShapeHash": "D0E16277",
      "planCacheKey": "C78E6493",
      "optimizationTimeMillis": 0,
      "maxIndexedOrSolutionsReached": false,
      "maxIndexedAndSolutionsReached": false,
      "maxScansToExplodeReached": false,
      "prunedSimilarIndexes": false,
      "winningPlan": {
        "isCached": false,
        "queryPlan": {
          "stage": "GROUP",
          "planNodeId": 3,
          "inputStage": {
            "stage": "PROJECTION_COVERED",
            "planNodeId": 2,
            "transformBy": {
              "nrSecao": true,
              "nrZona": true,
              "_id": false
            },
            "inputStage": {
              "stage": "IXSCAN",
              "planNodeId": 1,
              "keyPattern": {
                "tipo": 1,
                "nrZona": 1,
                "nrSecao": 1
              },
              "indexName": "tipo_1_nrZona_1_nrSecao_1",
              "isMultiKey": false,
              "multiKeyPaths": {
                "tipo": [],
                "nrZona": [],
                "nrSecao": []
              },
              "isUnique": false,
              "isSparse": false,
              "isPartial": false,
              "indexVersion": 2,
              "direction": "forward",
              "indexBounds": {
                "tipo": [
                  "[\"PCD\", \"PCD\"]"
                ],
                "nrZona": [
                  "[MinKey, MaxKey]"
                ],
                "nrSecao": [
                  "[MinKey, MaxKey]"
                ]
              }
            }
          }
        },
        "slotBasedPlan": {
          "slots": "$$RESULT=s8 env: {  }",
          "stages": "[3] project [s8 = newObj(\"_id\", s6, \"totalPCD\", s7)] \n[3] project [s6 = newObj(\"nrZona\", s1, \"nrSecao\", s2), s7 = (convert ( s5, int32) ?: s5)] \n[3] group [s1, s2] [s5 = count()] spillSlots[s4] mergingExprs[sum(s4)] \n[1] ixseek KS(3C504344000A0A0104) KS(3C50434400F0F0FE04) none s3 none none [s1 = 1, s2 = 2] @\"56b360ae-f3dd-4079-8b56-3ef241acf976\" @\"tipo_1_nrZona_1_nrSecao_1\" true "
        }
      },
      "rejectedPlans": [
        {
          "isCached": false,
          "stage": "PROJECTION_SIMPLE",
          "transformBy": {
            "nrSecao": 1,
            "nrZona": 1,
            "_id": 0
          },
          "inputStage": {
            "stage": "FETCH",
            "inputStage": {
              "stage": "IXSCAN",
              "keyPattern": {
                "tipo": 1
              },
              "indexName": "tipo_1",
              "isMultiKey": false,
              "multiKeyPaths": {
                "tipo": []
              },
              "isUnique": false,
              "isSparse": false,
              "isPartial": false,
              "indexVersion": 2,
              "direction": "forward",
              "indexBounds": {
                "tipo": [
                  "[\"PCD\", \"PCD\"]"
                ]
              }
            }
          }
        }
      ]
    },
    "executionStats": {
      "executionSuccess": true,
      "nReturned": 6515,
      "executionTimeMillis": 23,
      "totalKeysExamined": 12032,
      "totalDocsExamined": 0,
      "executionStages": {
        "stage": "project",
        "planNodeId": 3,
        "nReturned": 6515,
        "executionTimeMillisEstimate": 9,
        "opens": 1,
        "closes": 1,
        "saveState": 9,
        "restoreState": 9,
        "isEOF": 1,
        "projections": {
          "8": "newObj(\"_id\", s6, \"totalPCD\", s7) "
        },
        "inputStage": {
          "stage": "project",
          "planNodeId": 3,
          "nReturned": 6515,
          "executionTimeMillisEstimate": 9,
          "opens": 1,
          "closes": 1,
          "saveState": 9,
          "restoreState": 9,
          "isEOF": 1,
          "projections": {
            "6": "newObj(\"nrZona\", s1, \"nrSecao\", s2) ",
            "7": "(convert ( s5, int32) ?: s5) "
          },
          "inputStage": {
            "stage": "group",
            "planNodeId": 3,
            "nReturned": 6515,
            "executionTimeMillisEstimate": 9,
            "opens": 1,
            "closes": 1,
            "saveState": 9,
            "restoreState": 9,
            "isEOF": 1,
            "groupBySlots": [
              1,
              2
            ],
            "expressions": {
              "5": "count() ",
              "initExprs": {
                "5": null
              }
            },
            "mergingExprs": {
              "4": "sum(s4) "
            },
            "usedDisk": false,
            "spills": 0,
            "spilledBytes": 0,
            "spilledRecords": 0,
            "spilledDataStorageSize": 0,
            "inputStage": {
              "stage": "ixseek",
              "planNodeId": 1,
              "nReturned": 12032,
              "executionTimeMillisEstimate": 8,
              "opens": 1,
              "closes": 1,
              "saveState": 9,
              "restoreState": 9,
              "isEOF": 1,
              "indexName": "tipo_1_nrZona_1_nrSecao_1",
              "keysExamined": 12032,
              "seeks": 1,
              "numReads": 12033,
              "recordIdSlot": 3,
              "outputSlots": [
                1,
                2
              ],
              "indexKeysToInclude": "00000000000000000000000000000110",
              "seekKeyLow": "KS(3C504344000A0A0104) ",
              "seekKeyHigh": "KS(3C50434400F0F0FE04) "
            }
          }
        }
      }
    }
  },
  "nReturned": 6515,
  "executionTimeMillisEstimate": 21
}

### 6.7 Conclusão da investigação de performance

A investigação da lentidão na tabela `locais_votacao` confirmou, na
prática, os mesmos princípios já validados na Seção 5: índices eliminam
varreduras completas de coleção (COLLSCAN) e direcionam o MongoDB
diretamente aos documentos relevantes.

O processo evoluiu em três etapas:

| Cenário | Estágio do plano | Tempo de execução | Docs. examinados |
|---|---|---|---|
| Sem índice | COLLSCAN | 1759 ms | 904.077 |
| Índice simples (`tipo`) | IXSCAN → FETCH | 157 ms | 12.032 |
| Índice composto (`tipo, nrZona, nrSecao`) | IXSCAN → PROJECTION_COVERED | 26 ms | 0 |

O índice composto eliminou por completo a necessidade de abrir os
documentos originais (*covered query*), resultando em uma melhora de
aproximadamente **68 vezes** em relação ao cenário inicial.

**Lição principal:** um índice simples já resolve o gargalo do filtro
(`$match`), mas se a consulta também usa outros campos (no `$group`,
`$sort` ou projeção), um índice composto que inclua esses campos pode
eliminar até a etapa de busca do documento (`FETCH`), tornando a
consulta totalmente "coberta" pelo índice.

Detalhamento completo, incluindo os resultados brutos do `explain()`
de cada etapa, em `docs/Otimizacao_Indice_Perfis_Dashboard.md`.

## 7. Schema Design Pattern

### Polymorphic Pattern (aplicado em `perfis`)

A coleção `perfis` implementa o **Polymorphic Pattern** (aula 08): documentos de tipos
relacionados (PerfilPCD e PerfilNaoPCD) convivem na mesma coleção, discriminados pelo
campo `tipo`. Documentos `tipo: "PCD"` possuem o campo extra `qtEletoresDeficiencia`;
documentos `tipo: "NAO_PCD"` não o possuem.

**Justificativa da escolha:** os dois subtipos compartilham a maioria dos atributos
(gênero, faixa etária, escolaridade etc.) e são consultados **em conjunto** nas análises
comparativas do projeto (ex.: comparar abstenção PCD vs. não-PCD na mesma zona). Separar
em duas coleções exigiria `$lookup` ou consultas duplicadas em praticamente toda análise,
sem ganho real — o Polymorphic Pattern evita essa fragmentação, mantendo o esquema flexível
do MongoDB para o campo opcional `qtEletoresDeficiencia`.

**`$graphLookup` (não aplicável):** o modelo não possui relacionamento hierárquico
recursivo (município↔zona é N:N, resolvido por arrays de referência bidirecionais;
zona→seção é 1:N simples) — não há estrutura em árvore que justifique `$graphLookup`.